### ISSUE TITLE
Minor error in GSIM-2.0 Agent In Role

### ISSUE THREAD

**Issue by JALinnerud** [UNECE/GSIM-2.0#10]
1.2.3 has Agent in Role - It should be Agent In Role.

**Comment by PerWiklander** [comment]
Should it?
"in" is usually [not capitalised](https://prowritingaid.com/list-of-words-not-capitalized-in-titles#article-head3) in title case.

**Comment by JALinnerud** [comment]
GSIM v2 has 3 different information classes: Agent, Role and AgentInRole 
![image](https://github.com/UNECE/GSIM-2.0/assets/31731072/bc4144ef-296d-4bc8-b6c9-62e6593440c9)
The Base group diagram shows all three information classes
1.2.3 is describing the third class. I think it would be consistent to capitalise In, to make it clear that this section is describing that class.

**Comment by PerWiklander** [comment]
In two parts of the spec (the diagrams and the textual description) we have "Agent In Role" in one place and "Agent in Role" in the other.

- We both want consistency
- You advocate for "Agent In Role"
- I advocate for "Agent in Role"
- "AgentInRole" does not exist.

**Comment by JALinnerud** [comment]
It did exist in GSIM v1.2 see for example: https://statswiki.unece.org/display/gsim/GSIM+v1.2+Glossary

**Comment by Chris-ECE** [comment]
So to be clear, the outcome is a decision to replace any occurrences of "Agent In Role" with "Agent in Role"?

Thanks

**Comment by JALinnerud** [comment]
Not from me. I propose replacing Agent in Role in the html by Agent In Role. We have been trying to consistently use CamelCase. If we object to capitalising in to In then we could rename as Agent Fulfills Role, but I don't reccomend that. Could check with a GSIM modeller - Flavio, Francine - if in doubt about correct use of CamelCae...

**Comment by Chris-ECE** [comment]
Okay then. - I'll implement CamelCase for consistency.
