### ISSUE TITLE
Explanatory text for Statistical Need 

### ISSUE THREAD

**Issue by JALinnerud** [UNECE/GSIM-2.0#12]
The business group diagram 
https://unece.github.io/GSIM-2.0/GSIMv2.html#id21_business_group_group_diagram
shows Statistical Need as a sub-type of Environment Change. This is inconsistent with the explanatory text in GSIM v2 for Statistical Need "...A Statistical Need may be of a variety of types including Environment Change or Information Request." Note The explanartory text was consistent with the diagram in v1.2, but the diagram in v1.2 was changed and the explanatory text has not been changed.
Of course, it is possible that the diagram is wrong and the explanatory text is correct.
**Action:** Change the last sentence in the explantory text to ".A Statistical Need may be of a variety of types including Information Request".

**Comment by Chris-ECE** [comment]
Implemented
