### ISSUE TITLE
Duplicate relation in Conceptual UML diagram

### ISSUE THREAD

**Issue by JALinnerud** [UNECE/GSIM-2.0#14]
https://github.com/UNECE/GSIM-2.0/blob/main/UML%20Model%20Files/GSIM_2_0_Concepts_Group.drawio
There are two instances of the relationship between Statistical Program and Universe. The one on the top right of the attached image should be removed. Of course, Statistical Program should also be renamed to Statistical Programme.
![image](https://github.com/UNECE/GSIM-2.0/assets/31731072/90d07920-0df6-4024-8404-e7acc9ee9a6b)

**Comment by Chris-ECE** [comment]
Both corrections implemented.
