### ISSUE TITLE
Where is the source code for the documentation now?

### ISSUE THREAD

**Issue by PerWiklander** [UNECE/GSIM-2.0#4]
The new html file looks very nice and makes it easier to read the spec. But where is the source code? I assume the html is generated by a tool. How can we contribute changes now?

**Comment by InKyungChoi** [comment]
Hi @PerWiklander ! 

Glad to hear that html version looks better. 

The source code is actually the [html file itself](https://github.com/UNECE/GSIM-2.0/blob/main/GSIMv2.html) now. It had been "saved as (html)" from github webpage (https://unece.github.io/GSIM-2.0/) to get basic html tags, and additional formatting (using [Respec](https://respec.org/docs/) following other similar works) and edits were made directly to html file.

It is a bit more complicated to make changes, but if it is just for texts, you can make commits directly to html as with README.md file (e.g., https://github.com/UNECE/GSIM-2.0/commit/25b68925f3ba27657130ba7b5f3b43248ab80d45). If it is about images/formats, feel free to let us know through issues. 

\+  This online html viewer tool was helpful: https://codebeautify.org/htmlviewer.
