### ISSUE TITLE
Feature: Sticky sidebar

### ISSUE THREAD

**Issue by PerWiklander** [UNECE/GSIM-2.0#7]
While navigating around the spec it would be very nice to have the side bar available (sticky). As it is now it scrolls away with the content. Right now the browser search feature or two (or three) browser windows is the only way to jump between definitions of related objects.

**Comment by Chris-ECE** [comment]
In this page, there is a sticky sidebar: https://unece.github.io/GSIM-2.0/GSIMv2.html

I think you might have been referring to https://unece.github.io/ which has been addressed/discussed in Issue #5

Thanks

**Comment by PerWiklander** [comment]
I just tested Arc (Chrome based) and Safari on MacOS 14.5 and I do not have a sticky side bar at https://unece.github.io/GSIM-2.0/GSIMv2.html
